export const Size = {
  DEFAULT: "",
  SIZE12: "size-12",
  SIZE14: "size-14",
  SIZE16: "size-16",
  SIZE18: "size-18",
  SIZE20: "size-20",
  SIZE24: "size-24",
  SIZE32: "size-32",
  SIZE40: "size-40",
  SIZE48: "size-48",
  SIZE64: "size-64",
  SIZE96: "size-96",
  SIZE128: "size-128"
};

export const IconName = {
  PLUS: "plus",
  AVATAR: "Avatar",
  CHART: "3501shuju",
  CROSS: "cross",
  NOTE: "note",
  KEY: "key",
  TRASH: "trash",
  HOME: "mendianchaxun",
  LOADING: "loding",
  EYE: "eye",
  EYE_SLASH: "eye-slash",
  OMIT: "omit",
  SINGAPORE: "Singapore",
  LEFT: "left",
  RIGHT: "right",
  DOWN: "down",
  DOUBLE_LEFT: "doubleleft",
  DOUBLE_RIGHT: "doubleright",
  PAPER_PLANE: "PaperPlane",
  DROPLET: "droplet",
  WARNING: "warning-circle-fill",
  ERROR: "close-circle-fill",
  SUCCESS: "check-circle-fill",
  INFO: "info-circle-fill"
};
